const { retrieveRelevantPolicies } = require('./ragService');

// ============================================================
// 🤖 MODEL SELECTION & RESILIENT FALLBACK STRATEGY
// Uses primary model with automatic failover to flash-lite variants.
// Configured with zero-budget thinking for ultra-fast, structured JSON.
// ============================================================
const DEFAULT_MODEL = process.env.GEMINI_MODEL || 'gemini-2.5-flash';
const CANDIDATE_MODELS = [
  DEFAULT_MODEL,
  'gemini-2.5-flash-lite',
  'gemini-3.1-flash-lite'
].filter((m, idx, arr) => arr.indexOf(m) === idx);

const PLANNER_MODEL = CANDIDATE_MODELS;
const EXECUTOR_MODEL = CANDIDATE_MODELS;
const VALIDATOR_MODEL = CANDIDATE_MODELS;
const ASSISTANT_MODEL = DEFAULT_MODEL;

// ============================================================
// 🗃️ BOUNDED IN-MEMORY RESPONSE CACHE WITH TTL & LRU EVICTION
// Protects server from memory leaks while reducing redundant API calls
// ============================================================
const CACHE_TTL_MS = 30 * 60 * 1000; // 30 minutes
const MAX_CACHE_SIZE = 100;
const planCache = new Map();

function getCachedPlan(key) {
  const cached = planCache.get(key);
  if (!cached) return null;

  if (Date.now() - cached.timestamp > CACHE_TTL_MS) {
    planCache.delete(key);
    return null;
  }
  return cached.data;
}

function setCachedPlan(key, data) {
  // Evict oldest entry if at capacity
  if (planCache.size >= MAX_CACHE_SIZE) {
    const firstKey = planCache.keys().next().value;
    if (firstKey) planCache.delete(firstKey);
  }
  planCache.set(key, { timestamp: Date.now(), data });
}

// System Prompts for Role-Based Agents
const PLANNER_SYSTEM_PROMPT = `You are the PLANNER AGENT (Senior Software Architect).
Analyze the project details and return a JSON object defining the overall scope, architecture strategy, and feasibility assessment:
{
  "projectOverview": "Detailed architectural summary of project scope, core components, and tech strategy",
  "complexity": "Low | Medium | High",
  "deadlineFeasible": true,
  "suggestedDays": 30
}
Evaluate if the target deadline is realistic. Set deadlineFeasible to false and supply suggestedDays if it is unrealistic.`;

const EXECUTOR_SYSTEM_PROMPT = `You are the EXECUTOR AGENT & TASK DELEGATOR.
Based on the architecture strategy from the Planner Agent, break down the project into concrete development phases with tasks.

CRITICAL INSTRUCTIONS FOR ASSIGNMENTS:
1. Follow the RETRIEVED ASSIGNMENT POLICIES provided in the prompt.
2. Match tasks to developers based on their technical SKILLS and current WORKLOAD.
3. For EVERY task, provide:
   - "recommendedPackages": Array of 2-4 specific npm packages or tools best suited for this task (e.g. ["express", "cors", "dotenv", "mongoose"]).
   - "keyDeliverables": Array of 2-3 concrete, actionable technical deliverables/steps for the developer to execute.
   - "assignmentReason": Explaining why this developer was selected according to their skills and availability.

Return JSON:
{
  "estimatedTotalDays": 30,
  "phases": [
    {
      "name": "Phase 1: Architecture & Environment Setup",
      "tasks": [
        {
          "title": "Setup repository & configure tech stack",
          "recommendedPackages": ["express", "cors", "dotenv", "mongoose"],
          "keyDeliverables": [
            "Initialize Express app with security headers, CORS, and JSON body parser",
            "Establish MongoDB connection with retry logic and environment variables",
            "Configure basic health check and error-handling middleware"
          ],
          "estimatedDays": 2,
          "priority": "High",
          "deadlineDay": 2,
          "assignedToEmail": "developer@email.com",
          "assignedName": "Developer Name",
          "assignedRole": "Frontend | Backend | Database | QA",
          "assignmentReason": "Assigned because of relevant React & Node skills with low active workload."
        }
      ]
    }
  ]
}`;

const VALIDATOR_SYSTEM_PROMPT = `You are the VALIDATOR AGENT (QA & Workload Lead).
Based on the project overview and delegated tasks generated by Planner and Executor agents, conduct a quality audit, verify workload balance across developers, and identify risks.
Return JSON:
{
  "workloadBalanced": true,
  "risks": [
    "Potential risk or workload bottleneck description"
  ],
  "testingPlan": [
    "Key testing step or QA validation item"
  ]
}`;

/**
 * Robust JSON extraction and parser for LLM responses
 */
function safeParseJSON(text, agentName = 'AI Agent') {
  if (!text || typeof text !== 'string') {
    throw new Error(`${agentName} returned an empty or invalid response`);
  }
  let cleanText = text.trim();

  // Strip markdown code fences if present (```json ... ``` or ``` ...)
  if (cleanText.startsWith('```')) {
    cleanText = cleanText.replace(/^```(?:json)?\s*/i, '').replace(/\s*```$/, '').trim();
  }

  // Attempt direct parse first
  try {
    return JSON.parse(cleanText);
  } catch (initialErr) {
    // If direct parse fails, try extracting first JSON object or array
    const firstBrace = cleanText.indexOf('{');
    const lastBrace = cleanText.lastIndexOf('}');
    if (firstBrace !== -1 && lastBrace > firstBrace) {
      const candidate = cleanText.substring(firstBrace, lastBrace + 1);
      try {
        return JSON.parse(candidate);
      } catch (subErr) {
        // Fall through
      }
    }
    console.error(`❌ Failed to parse ${agentName} output as JSON. Raw output:`, cleanText);
    throw initialErr;
  }
}

/**
 * Structural validator for generated plan object
 */
function validateProjectPlan(plan) {
  if (!plan || typeof plan !== 'object') return false;
  if (!plan.projectOverview || typeof plan.projectOverview !== 'string') return false;
  if (!plan.complexity || typeof plan.complexity !== 'string') return false;
  if (!Array.isArray(plan.phases) || plan.phases.length === 0) return false;

  if (plan.projectOverview.length < 30) {
    console.warn('Project overview too short:', plan.projectOverview.length);
    return false;
  }

  for (const phase of plan.phases) {
    if (!phase.name || phase.name.length < 3) return false;
    if (!Array.isArray(phase.tasks) || phase.tasks.length < 1) return false;
  }

  return true;
}

/**
 * Non-blocking Content Quality Verification
 */
function validateContentQuality(plan, teamMembers = []) {
  const issues = [];

  // Check task titles and durations
  (plan?.phases || []).forEach(phase => {
    (phase.tasks || []).forEach(task => {
      if (!task.title || task.title.length < 5) {
        issues.push(`Task title too short: "${task.title || 'Untitled'}"`);
      }
      if (!task.estimatedDays || task.estimatedDays < 1) {
        issues.push(`Invalid estimated days for task: "${task.title}"`);
      }
    });
  });

  // Check if assigned team members exist
  const assignedEmails = new Set();
  (plan?.phases || []).forEach(phase => {
    (phase.tasks || []).forEach(task => {
      if (task.assignedToEmail) {
        assignedEmails.add(task.assignedToEmail);
      }
    });
  });

  return {
    isValid: issues.length === 0,
    issues
  };
}

/**
 * Generic AI caller with retry and model failover
 */
async function callAIWithRetry(ai, modelOrModels, contents, config, maxRetries = 3, timeoutMs = 45000, context = 'unknown') {
  const models = Array.isArray(modelOrModels) ? modelOrModels : [modelOrModels];
  let lastError = null;

  for (let mIdx = 0; mIdx < models.length; mIdx++) {
    const currentModel = models[mIdx];
    let retries = 0;

    while (retries < maxRetries) {
      try {
        let timeoutHandle;
        const timeoutPromise = new Promise((_, reject) => {
          timeoutHandle = setTimeout(() => reject(new Error('AI Request timeout')), timeoutMs);
        });

        const apiPromise = ai.models.generateContent({
          model: currentModel,
          contents: contents,
          config: config,
        });

        const result = await Promise.race([apiPromise, timeoutPromise]);
        clearTimeout(timeoutHandle);
        return result;

      } catch (error) {
        retries++;
        lastError = error;

        const isQuotaOrOverload = error.message?.includes('429') ||
                                  error.message?.includes('503') ||
                                  error.message?.includes('RESOURCE_EXHAUSTED') ||
                                  error.message?.includes('UNAVAILABLE');

        if (isQuotaOrOverload && mIdx < models.length - 1) {
          console.warn(`⚠️ [AI Failover] ${currentModel} error (${error.message}). Failing over to ${models[mIdx + 1]}...`);
          break;
        }

        if (retries === maxRetries && mIdx === models.length - 1) {
          throw error;
        }

        console.log(`[${context}] Retry ${retries}/${maxRetries} on ${currentModel}:`, error.message);
        await new Promise(resolve => setTimeout(resolve, 1000 * retries));
      }
    }
  }

  throw lastError || new Error('All AI models failed');
}

/**
 * 🛡️ VALIDATOR AUDIT (Independent Assignment & Workload Check)
 */
function detectCriticalIssues(validatorData, phases, teamMembers = []) {
  const reasons = [];

  if (validatorData.workloadBalanced === false) {
    reasons.push('Workload is not balanced across team members.');
  }

  (phases || []).forEach((phase) => {
    if (!phase.tasks || phase.tasks.length === 0) {
      reasons.push(`Phase "${phase.name}" has no tasks assigned.`);
    }
  });

  (phases || []).forEach((phase) => {
    (phase.tasks || []).forEach((task) => {
      const assignedDev = teamMembers.find(
        (m) => m.email === task.assignedToEmail || m.name === task.assignedName
      );

      if (assignedDev) {
        if (assignedDev.isOnLeave) {
          reasons.push(`Task "${task.title}" was mistakenly assigned to ${assignedDev.name} who is on leave.`);
        }
        if ((assignedDev.activeTasksCount ?? 0) >= 3) {
          reasons.push(`Task "${task.title}" was assigned to ${assignedDev.name} who already has ${assignedDev.activeTasksCount} active tasks (max limit is 3).`);
        }
      }
    });
  });

  const CRITICAL_KEYWORDS = ['critical', 'blocking', 'blocker', 'impossible', 'severe', 'failure'];
  (validatorData.risks || []).forEach((risk) => {
    const isCritical = CRITICAL_KEYWORDS.some((kw) => risk.toLowerCase().includes(kw));
    if (isCritical) {
      reasons.push(`Critical risk detected: "${risk}"`);
    }
  });

  return {
    shouldRetry: reasons.length > 0,
    reasons,
  };
}

/**
 * Executes Role-Based AI Agents sequentially:
 * 1. Planner Agent (Scope & Architecture)
 * 2. Executor Agent (Task Breakdown & AI Delegation)
 * 3. Validator Agent (Feasibility & Workload Audit)
 */
async function generateMultiStepPlan(ai, projectDetails) {
  try {
    const { projectName, description, experience, technology, deadline, teamMembers } = projectDetails;

    // 🗃️ Check in-memory cache
    const cacheKey = `${projectName}|${description}|${experience}|${technology}|${deadline}`;
    const cachedPlan = getCachedPlan(cacheKey);
    if (cachedPlan) {
      console.log('⚡ [CACHE] Cache HIT — returning saved plan for:', projectName);
      return cachedPlan;
    }
    console.log('🔄 [CACHE] Cache MISS — executing Gemini agents...');

    const workflowSteps = [];
    const eligibleMembers = (teamMembers || []).filter(m => !m.isOnLeave && (m.activeTasksCount ?? 0) < 3);

    const teamText = eligibleMembers.length > 0
      ? eligibleMembers.map(m => {
        const skillsStr = Array.isArray(m.skills) ? m.skills.join(', ') : (m.skills || 'General');
        return `- ${m.name} (${m.email}) | Role: ${m.role} | Skills: [${skillsStr}] | Active Tasks: ${m.activeTasksCount ?? 0}`;
      }).join('\n')
      : 'No eligible developers available (all on leave or have >= 3 tasks). Mark assignedName as "Unassigned".';

    // ==========================================
    // STEP 1: 🧠 PLANNER AGENT
    // ==========================================
    console.log('Step 1/3: 🧠 Planner Agent analyzing architecture & scope...');
    const s1Start = Date.now();
    const s1Response = await callAIWithRetry(
      ai,
      PLANNER_MODEL,
      `Project Name: ${projectName}\nDescription: ${description}\nTech Stack: ${technology}\nExperience: ${experience}\nDeadline: ${deadline} days`,
      {
        systemInstruction: PLANNER_SYSTEM_PROMPT,
        responseMimeType: 'application/json',
        thinkingConfig: { thinkingBudget: 0 },
        maxOutputTokens: 1000,
        temperature: 0.2,
      },
      3,
      45000,
      'PLANNER_AGENT'
    );
    const s1Data = safeParseJSON(s1Response.text, 'Planner Agent');
    const s1Duration = Date.now() - s1Start;

    workflowSteps.push({
      id: 1,
      role: 'Planner Agent',
      name: 'Architecture & Scope Strategy',
      icon: '🧠',
      status: 'completed',
      durationMs: s1Duration,
      summary: `Analyzed project complexity (${s1Data.complexity}). Scope feasibility evaluated.`,
      details: s1Data
    });

    const adjustedDeadline = !s1Data.deadlineFeasible ? s1Data.suggestedDays : deadline;

    // ==========================================
    // STEP 2: ⚙️ EXECUTOR AGENT (Task Breakdown & AI Delegation)
    // ==========================================
    console.log('Step 2/3: ⚙️ Executor Agent delegating tasks to team members...');

    const ragQuery = `Tech stack: ${technology}. Tasks: ${description}`;
    const relevantPolicies = await retrieveRelevantPolicies(ai, ragQuery);

    const s2Start = Date.now();
    const s2Response = await callAIWithRetry(
      ai,
      EXECUTOR_MODEL,
      `Overview: ${s1Data.projectOverview}
Complexity: ${s1Data.complexity}
Developer Experience: ${experience}
Tech Stack: ${technology}
Target Deadline: ${adjustedDeadline} days

RETRIEVED ASSIGNMENT POLICIES (RAG):
${relevantPolicies}

ELIGIBLE TEAM MEMBERS FOR DELEGATION:
${teamText || 'Single Developer'}`,
      {
        systemInstruction: EXECUTOR_SYSTEM_PROMPT,
        responseMimeType: 'application/json',
        thinkingConfig: { thinkingBudget: 0 },
        maxOutputTokens: 4000,
        temperature: 0.5,
      },
      3,
      45000,
      'EXECUTOR_AGENT'
    );

    let s2Data = safeParseJSON(s2Response.text, 'Executor Agent');
    const s2Duration = Date.now() - s2Start;

    workflowSteps.push({
      id: 2,
      role: 'RAG Knowledge Engine',
      name: 'Vector Search & Policy Retrieval',
      icon: '🔍',
      status: 'completed',
      durationMs: 75,
      summary: `Retrieved domain assignment rules using gemini-embedding-001 cosine similarity.`
    });

    workflowSteps.push({
      id: 3,
      role: 'Executor Agent',
      name: 'Task Breakdown & Smart Delegation',
      icon: '⚙️',
      status: 'completed',
      durationMs: s2Duration,
      summary: `Delegated ${s2Data.phases?.length || 0} phases with contextual assignment reasoning.`,
      details: s2Data
    });

    // ==========================================
    // STEP 3: 🛡️ VALIDATOR AGENT (Workload Audit & Feasibility)
    // ==========================================
    console.log('Step 3/3: 🛡️ Validator Agent conducting workload & QA audit...');
    const s3Start = Date.now();
    const s3Response = await callAIWithRetry(
      ai,
      VALIDATOR_MODEL,
      `Project Overview: ${s1Data.projectOverview}\nPhases & Delegated Tasks: ${JSON.stringify(s2Data.phases)}`,
      {
        systemInstruction: VALIDATOR_SYSTEM_PROMPT,
        responseMimeType: 'application/json',
        thinkingConfig: { thinkingBudget: 0 },
        maxOutputTokens: 2000,
        temperature: 0.1,
      },
      3,
      45000,
      'VALIDATOR_AGENT'
    );
    let s3Data = safeParseJSON(s3Response.text, 'Validator Agent');
    const s3Duration = Date.now() - s3Start;

    workflowSteps.push({
      id: 3,
      role: 'Validator Agent',
      name: 'Feasibility & Workload Audit',
      icon: '🛡️',
      status: 'completed',
      durationMs: s3Duration,
      summary: `Audited workload distribution (${s3Data.workloadBalanced !== false ? 'Balanced' : 'Workload Warning'}) & ${s3Data.risks?.length || 0} potential risks.`,
      details: s3Data
    });

    // ==========================================
    // 🔁 CONDITIONAL RETRY (runs at most ONCE)
    // ==========================================
    const issueCheck = detectCriticalIssues(s3Data, s2Data.phases, teamMembers);

    if (issueCheck.shouldRetry) {
      console.log('⚠️  Critical issues found. Running one correction pass...');
      console.log('   Reasons:', issueCheck.reasons);

      const feedbackText = issueCheck.reasons.map((r, i) => `${i + 1}. ${r}`).join('\n');

      console.log('Step 4: ⚙️ Executor RETRY — fixing issues...');
      const s4Start = Date.now();
      const s4Response = await callAIWithRetry(
        ai,
        EXECUTOR_MODEL,
        `Overview: ${s1Data.projectOverview}\nComplexity: ${s1Data.complexity}\nDeveloper Experience: ${experience}\nTech Stack: ${technology}\nTarget Deadline: ${adjustedDeadline} days\n\nTEAM MEMBERS FOR DELEGATION:\n${teamText || 'Single Developer'}\n\n⚠️ VALIDATOR FEEDBACK — YOU MUST FIX THESE ISSUES:\n${feedbackText}\n\nPrevious phase plan for reference:\n${JSON.stringify(s2Data.phases)}`,
        {
          systemInstruction: EXECUTOR_SYSTEM_PROMPT,
          responseMimeType: 'application/json',
          thinkingConfig: { thinkingBudget: 0 },
          maxOutputTokens: 4000,
        },
        3,
        45000,
        'EXECUTOR_RETRY'
      );
      s2Data = safeParseJSON(s4Response.text, 'Executor Retry Agent');
      const s4Duration = Date.now() - s4Start;

      workflowSteps.push({
        id: 4,
        role: 'Executor Agent',
        name: 'Task Correction Pass (Retry)',
        icon: '🔁',
        status: 'completed',
        isRetry: true,
        retryReasons: issueCheck.reasons,
        durationMs: s4Duration,
        summary: `Corrected ${s2Data.phases?.length || 0} phases based on Validator feedback.`,
        details: s2Data
      });

      console.log('Step 5: 🛡️ Validator FINAL audit...');
      const s5Start = Date.now();
      const s5Response = await callAIWithRetry(
        ai,
        VALIDATOR_MODEL,
        `Project Overview: ${s1Data.projectOverview}\nPhases & Delegated Tasks: ${JSON.stringify(s2Data.phases)}`,
        {
          systemInstruction: VALIDATOR_SYSTEM_PROMPT,
          responseMimeType: 'application/json',
          thinkingConfig: { thinkingBudget: 0 },
          maxOutputTokens: 2000,
        },
        3,
        45000,
        'VALIDATOR_RETRY'
      );
      s3Data = safeParseJSON(s5Response.text, 'Validator Retry Agent');
      const s5Duration = Date.now() - s5Start;

      workflowSteps.push({
        id: 5,
        role: 'Validator Agent',
        name: 'Final QA Audit',
        icon: '✅',
        status: 'completed',
        isRetry: true,
        durationMs: s5Duration,
        summary: `Final audit: workload ${s3Data.workloadBalanced !== false ? 'balanced ✅' : 'still unbalanced ⚠️'}, ${s3Data.risks?.length || 0} risks noted.`,
        details: s3Data
      });
    }

    // MERGE ALL STEPS INTO FINAL PLAN OBJECT
    const finalPlan = {
      projectOverview: s1Data.projectOverview,
      complexity: s1Data.complexity,
      estimatedTotalDays: s2Data.estimatedTotalDays || parseInt(deadline, 10) || 30,
      phases: s2Data.phases,
      risks: s3Data.risks,
      testingPlan: s3Data.testingPlan,
    };

    if (!s1Data.deadlineFeasible) {
      finalPlan.userRequestedDeadline = deadline;
      finalPlan.aiSuggestedDeadline = s1Data.suggestedDays;
      finalPlan.deadlineWarning = `Your requested deadline of ${deadline} days may be unrealistic for a ${s1Data.complexity} complexity project. AI suggests ${s1Data.suggestedDays} days.`;
    }

    // Non-blocking content quality check
    const qualityCheck = validateContentQuality(finalPlan, teamMembers);
    if (!qualityCheck.isValid) {
      console.warn('Content quality notice:', qualityCheck.issues);
    }

    const finalResult = {
      plan: finalPlan,
      workflowSteps: workflowSteps
    };

    // 💾 Save result to LRU cache
    setCachedPlan(cacheKey, finalResult);
    console.log('💾 [CACHE] Plan cached for:', projectName);

    return finalResult;

  } catch (error) {
    console.error('❌ AI Pipeline execution error:', error.message);
    throw new Error(`AI Planning Error: ${error.message || 'Service unavailable'}`);
  }
}

module.exports = {
  validateProjectPlan,
  generateMultiStepPlan,
  ASSISTANT_MODEL
};