const { retrieveRelevantPolicies } = require('./ragService');

// ============================================================
// 🤖 LLM PROVIDER CONFIGURATIONS (Ollama Primary + OpenRouter Fallback)
// ============================================================
const OLLAMA_BASE_URL = process.env.OLLAMA_BASE_URL;
const OLLAMA_MODEL = process.env.OLLAMA_MODEL;

const OPENROUTER_API_KEY = process.env.OPENROUTER_API_KEY;
const OPENROUTER_BASE_URL = process.env.OPENROUTER_BASE_URL;
const OPENROUTER_MODEL = process.env.OPENROUTER_MODEL;

// ============================================================
// 🗃️ BOUNDED IN-MEMORY RESPONSE CACHE WITH TTL & LRU EVICTION
// Protects server from memory leaks while reducing redundant API calls
// ============================================================
const CACHE_TTL_MS = 30 * 60 * 1000; // 30 minutes
const MAX_CACHE_SIZE = 100;
const planCache = new Map();

function getCachedPlan(key) {
  const cached = planCache.get(key);
  if (!cached) return null;

  if (Date.now() - cached.timestamp > CACHE_TTL_MS) {
    planCache.delete(key);
    return null;
  }
  return cached.data;
}

function setCachedPlan(key, data) {
  // Evict oldest entry if at capacity
  if (planCache.size >= MAX_CACHE_SIZE) {
    const firstKey = planCache.keys().next().value;
    if (firstKey) planCache.delete(firstKey);
  }
  planCache.set(key, { timestamp: Date.now(), data });
}

// System Prompts for Role-Based Agents
const PLANNER_SYSTEM_PROMPT = `You are the PLANNER AGENT (Senior Software Architect).
Analyze the project details and return a JSON object defining the overall scope, architecture strategy, and feasibility assessment:
{
  "projectOverview": "Detailed architectural summary of project scope, core components, and tech strategy",
  "complexity": "Low | Medium | High",
  "deadlineFeasible": true,
  "suggestedDays": 30
}
Evaluate if the target deadline is realistic. Set deadlineFeasible to false and supply suggestedDays if it is unrealistic.`;

const EXECUTOR_SYSTEM_PROMPT = `You are the EXECUTOR AGENT & TASK DELEGATOR.
Based on the architecture strategy from the Planner Agent, break down the project into concrete development phases with tasks.

CRITICAL INSTRUCTIONS FOR ASSIGNMENTS:
1. Follow the RETRIEVED ASSIGNMENT POLICIES provided in the prompt.
2. Match tasks to developers based on their technical SKILLS and current WORKLOAD.
3. For EVERY task, provide:
   - "recommendedPackages": Array of 2-4 specific npm packages or tools best suited for this task (e.g. ["express", "cors", "dotenv", "mongoose"]).
   - "keyDeliverables": Array of 2-3 concrete, actionable technical deliverables/steps for the developer to execute.
   - "assignmentReason": Explaining why this developer was selected according to their skills and availability.

Return JSON:
{
  "estimatedTotalDays": 30,
  "phases": [
    {
      "name": "Phase 1: Architecture & Environment Setup",
      "tasks": [
        {
          "title": "Setup repository & configure tech stack",
          "recommendedPackages": ["express", "cors", "dotenv", "mongoose"],
          "keyDeliverables": [
            "Initialize Express app with security headers, CORS, and JSON body parser",
            "Establish MongoDB connection with retry logic and environment variables",
            "Configure basic health check and error-handling middleware"
          ],
          "estimatedDays": 2,
          "priority": "High",
          "deadlineDay": 2,
          "assignedToEmail": "developer@email.com",
          "assignedName": "Developer Name",
          "assignedRole": "Frontend | Backend | Database | QA",
          "assignmentReason": "Assigned because of relevant React & Node skills with low active workload."
        }
      ]
    }
  ]
}`;

const VALIDATOR_SYSTEM_PROMPT = `You are the VALIDATOR AGENT (QA & Workload Lead).
Based on the project overview and delegated tasks generated by Planner and Executor agents, conduct a quality audit, verify workload balance across developers, and identify risks.
Return JSON:
{
  "workloadBalanced": true,
  "risks": [
    "Potential risk or workload bottleneck description"
  ],
  "testingPlan": [
    "Key testing step or QA validation item"
  ]
}`;

/**
 * Robust JSON extraction and parser for LLM responses
 */
function safeParseJSON(text, agentName = 'AI Agent') {
  if (!text || typeof text !== 'string') {
    throw new Error(`${agentName} returned an empty or invalid response`);
  }
  let cleanText = text.trim();

  // Strip markdown code fences if present (```json ... ``` or ``` ...)
  if (cleanText.startsWith('```')) {
    cleanText = cleanText.replace(/^```(?:json)?\s*/i, '').replace(/\s*```$/, '').trim();
  }

  // Attempt direct parse first
  try {
    return JSON.parse(cleanText);
  } catch (initialErr) {
    // If direct parse fails, try extracting first JSON object or array
    const firstBrace = cleanText.indexOf('{');
    const lastBrace = cleanText.lastIndexOf('}');
    if (firstBrace !== -1 && lastBrace > firstBrace) {
      const candidate = cleanText.substring(firstBrace, lastBrace + 1);
      try {
        return JSON.parse(candidate);
      } catch (subErr) {
        // Fall through
      }
    }
    console.error(`❌ Failed to parse ${agentName} output as JSON. Raw output:`, cleanText);
    throw initialErr;
  }
}

/**
 * Structural validator for generated plan object
 */
function validateProjectPlan(plan) {
  if (!plan || typeof plan !== 'object') return false;
  if (!plan.projectOverview || typeof plan.projectOverview !== 'string') return false;
  if (!plan.complexity || typeof plan.complexity !== 'string') return false;
  if (!Array.isArray(plan.phases) || plan.phases.length === 0) return false;

  if (plan.projectOverview.length < 20) {
    console.warn('Project overview too short:', plan.projectOverview.length);
    return false;
  }

  for (const phase of plan.phases) {
    if (!phase.name || phase.name.length < 3) return false;
    if (!Array.isArray(phase.tasks) || phase.tasks.length < 1) return false;
  }

  return true;
}

/**
 * Non-blocking Content Quality Verification
 */
function validateContentQuality(plan, teamMembers = []) {
  const issues = [];

  (plan?.phases || []).forEach(phase => {
    (phase.tasks || []).forEach(task => {
      if (!task.title || task.title.length < 5) {
        issues.push(`Task title too short: "${task.title || 'Untitled'}"`);
      }
      if (!task.estimatedDays || task.estimatedDays < 1) {
        issues.push(`Invalid estimated days for task: "${task.title}"`);
      }
    });
  });

  const assignedEmails = new Set();
  (plan?.phases || []).forEach(phase => {
    (phase.tasks || []).forEach(task => {
      if (task.assignedToEmail) {
        assignedEmails.add(task.assignedToEmail);
      }
    });
  });

  return {
    isValid: issues.length === 0,
    issues
  };
}

/**
 * 1. Primary: Call local Ollama instance
 */
async function callOllamaWithRetry({
  model = OLLAMA_MODEL,
  systemPrompt,
  userPrompt,
  temperature = 0.2,
  format = 'json',
  maxRetries = 2,
  timeoutMs = 60000,
  context = 'unknown'
}) {
  let lastError = null;

  for (let attempt = 1; attempt <= maxRetries; attempt++) {
    try {
      const controller = new AbortController();
      const timeoutHandle = setTimeout(() => controller.abort(), timeoutMs);

      const requestBody = {
        model: model,
        messages: [
          ...(systemPrompt ? [{ role: 'system', content: systemPrompt }] : []),
          { role: 'user', content: userPrompt }
        ],
        stream: false,
        options: {
          temperature: temperature
        }
      };

      if (format) {
        requestBody.format = format;
      }

      const response = await fetch(`${OLLAMA_BASE_URL}/api/chat`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(requestBody),
        signal: controller.signal
      });

      clearTimeout(timeoutHandle);

      if (!response.ok) {
        const errorText = await response.text();
        throw new Error(`Ollama HTTP ${response.status}: ${errorText || response.statusText}`);
      }

      const data = await response.json();
      const content = data.message?.content || data.response || '';
      return { text: content, provider: `Ollama (${model})` };

    } catch (error) {
      lastError = error;
      console.warn(`⚠️ [${context}] Attempt ${attempt}/${maxRetries} on Ollama (${model}) failed: ${error.message}`);

      if (attempt === maxRetries) {
        throw error;
      }
      await new Promise(resolve => setTimeout(resolve, 800 * attempt));
    }
  }

  throw lastError || new Error(`Failed to get response from Ollama for ${context}`);
}

/**
 * 2. Fallback: Call OpenRouter (openai/gpt-4o)
 */
async function callOpenRouterWithRetry({
  model = OPENROUTER_MODEL,
  systemPrompt,
  userPrompt,
  temperature = 0.2,
  format = 'json',
  maxTokens = 2500,
  maxRetries = 2,
  timeoutMs = 45000,
  context = 'unknown'
}) {
  if (!OPENROUTER_API_KEY) {
    throw new Error('OPENROUTER_API_KEY is not configured for fallback');
  }

  let lastError = null;

  for (let attempt = 1; attempt <= maxRetries; attempt++) {
    try {
      const controller = new AbortController();
      const timeoutHandle = setTimeout(() => controller.abort(), timeoutMs);

      const requestBody = {
        model: model,
        messages: [
          ...(systemPrompt ? [{ role: 'system', content: systemPrompt }] : []),
          { role: 'user', content: userPrompt }
        ],
        temperature: temperature,
        max_tokens: maxTokens
      };

      if (format === 'json') {
        requestBody.response_format = { type: 'json_object' };
      }

      const response = await fetch(`${OPENROUTER_BASE_URL}/chat/completions`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${OPENROUTER_API_KEY}`,
          'HTTP-Referer': 'http://localhost:5000',
          'X-Title': 'AI Project Planner'
        },
        body: JSON.stringify(requestBody),
        signal: controller.signal
      });

      clearTimeout(timeoutHandle);

      if (!response.ok) {
        const errorText = await response.text();
        throw new Error(`OpenRouter HTTP ${response.status}: ${errorText || response.statusText}`);
      }

      const data = await response.json();
      const content = data.choices?.[0]?.message?.content || '';
      return { text: content, provider: `OpenRouter (${model})` };

    } catch (error) {
      lastError = error;
      console.warn(`⚠️ [${context}] Attempt ${attempt}/${maxRetries} on OpenRouter (${model}) failed: ${error.message}`);

      if (attempt === maxRetries) {
        throw error;
      }
      await new Promise(resolve => setTimeout(resolve, 800 * attempt));
    }
  }

  throw lastError || new Error(`Failed to get response from OpenRouter for ${context}`);
}

/**
 * Unified LLM Runner with Automatic Failover:
 * 1. Tries local Ollama (llama3.2)
 * 2. If Ollama fails, automatically falls back to OpenRouter (openai/gpt-4o)
 */
async function callLLMWithFallback({
  systemPrompt,
  userPrompt,
  temperature = 0.2,
  format = 'json',
  maxTokens = 2500,
  context = 'unknown'
}) {
  try {
    return await callOllamaWithRetry({
      model: OLLAMA_MODEL,
      systemPrompt,
      userPrompt,
      temperature,
      format,
      maxRetries: 2,
      timeoutMs: 45000,
      context
    });
  } catch (ollamaErr) {
    console.warn(`🔄 [LLM Failover] Ollama failed (${ollamaErr.message}). Failing over to OpenRouter (${OPENROUTER_MODEL})...`);
    try {
      const openRouterRes = await callOpenRouterWithRetry({
        model: OPENROUTER_MODEL,
        systemPrompt,
        userPrompt,
        temperature,
        format,
        maxTokens,
        maxRetries: 2,
        timeoutMs: 45000,
        context: `${context}_FALLBACK`
      });
      console.log(`✅ [LLM Failover] Successfully generated via OpenRouter (${OPENROUTER_MODEL}) for ${context}`);
      return openRouterRes;
    } catch (fallbackErr) {
      console.error(`❌ Both Ollama and OpenRouter fallback failed for ${context}:`, fallbackErr.message);
      throw new Error(`AI Generation Failed: Ollama (${ollamaErr.message}) & OpenRouter (${fallbackErr.message})`);
    }
  }
}

/**
 * 🛡️ VALIDATOR AUDIT (Independent Assignment & Workload Check)
 */
function detectCriticalIssues(validatorData, phases, teamMembers = []) {
  const reasons = [];

  if (validatorData.workloadBalanced === false) {
    reasons.push('Workload is not balanced across team members.');
  }

  (phases || []).forEach((phase) => {
    if (!phase.tasks || phase.tasks.length === 0) {
      reasons.push(`Phase "${phase.name}" has no tasks assigned.`);
    }
  });

  (phases || []).forEach((phase) => {
    (phase.tasks || []).forEach((task) => {
      const assignedDev = teamMembers.find(
        (m) => m.email === task.assignedToEmail || m.name === task.assignedName
      );

      if (assignedDev) {
        if (assignedDev.isOnLeave) {
          reasons.push(`Task "${task.title}" was mistakenly assigned to ${assignedDev.name} who is on leave.`);
        }
        if ((assignedDev.activeTasksCount ?? 0) >= 3) {
          reasons.push(`Task "${task.title}" was assigned to ${assignedDev.name} who already has ${assignedDev.activeTasksCount} active tasks (max limit is 3).`);
        }
      }
    });
  });

  const CRITICAL_KEYWORDS = ['critical', 'blocking', 'blocker', 'impossible', 'severe', 'failure'];
  (validatorData.risks || []).forEach((risk) => {
    const isCritical = CRITICAL_KEYWORDS.some((kw) => risk.toLowerCase().includes(kw));
    if (isCritical) {
      reasons.push(`Critical risk detected: "${risk}"`);
    }
  });

  return {
    shouldRetry: reasons.length > 0,
    reasons,
  };
}

/**
 * Executes Role-Based AI Agents sequentially with Ollama + OpenRouter Fallback:
 * 1. Planner Agent (Scope & Architecture)
 * 2. Executor Agent (Task Breakdown & AI Delegation)
 * 3. Validator Agent (Feasibility & Workload Audit)
 */
async function generateMultiStepPlan(ai, projectDetails) {
  try {
    const { projectName, description, experience, technology, deadline, teamMembers } = projectDetails;

    // 🗃️ Check in-memory cache
    const cacheKey = `${projectName}|${description}|${experience}|${technology}|${deadline}`;
    const cachedPlan = getCachedPlan(cacheKey);
    if (cachedPlan) {
      console.log('⚡ [CACHE] Cache HIT — returning saved plan for:', projectName);
      return cachedPlan;
    }
    console.log(`🔄 [CACHE] Cache MISS — executing agents (Primary: ${OLLAMA_MODEL} | Fallback: ${OPENROUTER_MODEL})...`);

    const workflowSteps = [];
    const eligibleMembers = (teamMembers || []).filter(m => !m.isOnLeave && (m.activeTasksCount ?? 0) < 3);

    const teamText = eligibleMembers.length > 0
      ? eligibleMembers.map(m => {
        const skillsStr = Array.isArray(m.skills) ? m.skills.join(', ') : (m.skills || 'General');
        return `- ${m.name} (${m.email}) | Role: ${m.role} | Skills: [${skillsStr}] | Active Tasks: ${m.activeTasksCount ?? 0}`;
      }).join('\n')
      : 'No eligible developers available (all on leave or have >= 3 tasks). Mark assignedName as "Unassigned".';

    // ==========================================
    // STEP 1: 🧠 PLANNER AGENT
    // ==========================================
    console.log(`Step 1/3: 🧠 Planner Agent analyzing architecture & scope...`);
    const s1Start = Date.now();
    const s1Response = await callLLMWithFallback({
      systemPrompt: PLANNER_SYSTEM_PROMPT,
      userPrompt: `Project Name: ${projectName}\nDescription: ${description}\nTech Stack: ${technology}\nExperience: ${experience}\nDeadline: ${deadline} days`,
      temperature: 0.2,
      format: 'json',
      maxTokens: 1200,
      context: 'PLANNER_AGENT'
    });
    const s1Data = safeParseJSON(s1Response.text, 'Planner Agent');
    const s1Duration = Date.now() - s1Start;

    workflowSteps.push({
      id: 1,
      role: `Planner Agent [${s1Response.provider}]`,
      name: 'Architecture & Scope Strategy',
      icon: '🧠',
      status: 'completed',
      durationMs: s1Duration,
      summary: `Analyzed project complexity (${s1Data.complexity}). Scope feasibility evaluated.`,
      details: s1Data
    });

    const adjustedDeadline = !s1Data.deadlineFeasible ? s1Data.suggestedDays : deadline;

    // ==========================================
    // STEP 2: ⚙️ EXECUTOR AGENT (Delegation)
    // ==========================================
    console.log(`Step 2/3: ⚙️ Executor Agent delegating tasks...`);

    const ragQuery = `Tech stack: ${technology}. Tasks: ${description}`;
    const relevantPolicies = await retrieveRelevantPolicies(ai, ragQuery);

    const s2Start = Date.now();
    const s2Response = await callLLMWithFallback({
      systemPrompt: EXECUTOR_SYSTEM_PROMPT,
      userPrompt: `Overview: ${s1Data.projectOverview}
Complexity: ${s1Data.complexity}
Developer Experience: ${experience}
Tech Stack: ${technology}
Target Deadline: ${adjustedDeadline} days

RETRIEVED ASSIGNMENT POLICIES (RAG):
${relevantPolicies}

ELIGIBLE TEAM MEMBERS FOR DELEGATION:
${teamText || 'Single Developer'}`,
      temperature: 0.3,
      format: 'json',
      maxTokens: 3000,
      context: 'EXECUTOR_AGENT'
    });

    let s2Data = safeParseJSON(s2Response.text, 'Executor Agent');
    const s2Duration = Date.now() - s2Start;

    workflowSteps.push({
      id: 2,
      role: 'RAG Knowledge Engine',
      name: 'Policy Retrieval & Vector Matching',
      icon: '🔍',
      status: 'completed',
      durationMs: 35,
      summary: `Retrieved domain assignment rules and developer capacity policies from data/policies.json.`
    });

    workflowSteps.push({
      id: 3,
      role: `Executor Agent [${s2Response.provider}]`,
      name: 'Task Breakdown & Smart Delegation',
      icon: '⚙️',
      status: 'completed',
      durationMs: s2Duration,
      summary: `Delegated ${s2Data.phases?.length || 0} phases with contextual assignment reasoning.`,
      details: s2Data
    });

    // ==========================================
    // STEP 3: 🛡️ VALIDATOR AGENT
    // ==========================================
    console.log(`Step 3/3: 🛡️ Validator Agent conducting workload & QA audit...`);
    const s3Start = Date.now();
    const s3Response = await callLLMWithFallback({
      systemPrompt: VALIDATOR_SYSTEM_PROMPT,
      userPrompt: `Project Overview: ${s1Data.projectOverview}\nPhases & Delegated Tasks: ${JSON.stringify(s2Data.phases)}`,
      temperature: 0.1,
      format: 'json',
      maxTokens: 1500,
      context: 'VALIDATOR_AGENT'
    });
    let s3Data = safeParseJSON(s3Response.text, 'Validator Agent');
    const s3Duration = Date.now() - s3Start;

    workflowSteps.push({
      id: 4,
      role: `Validator Agent [${s3Response.provider}]`,
      name: 'Feasibility & Workload Audit',
      icon: '🛡️',
      status: 'completed',
      durationMs: s3Duration,
      summary: `Audited workload distribution (${s3Data.workloadBalanced !== false ? 'Balanced' : 'Workload Warning'}) & ${s3Data.risks?.length || 0} potential risks.`,
      details: s3Data
    });

    // ==========================================
    // 🔁 CONDITIONAL RETRY (runs at most ONCE)
    // ==========================================
    const issueCheck = detectCriticalIssues(s3Data, s2Data.phases, teamMembers);

    if (issueCheck.shouldRetry) {
      console.log('⚠️  Critical issues found. Running one correction pass...');
      console.log('   Reasons:', issueCheck.reasons);

      const feedbackText = issueCheck.reasons.map((r, i) => `${i + 1}. ${r}`).join('\n');

      console.log('Step 4: ⚙️ Executor RETRY — fixing issues...');
      const s4Start = Date.now();
      const s4Response = await callLLMWithFallback({
        systemPrompt: EXECUTOR_SYSTEM_PROMPT,
        userPrompt: `Overview: ${s1Data.projectOverview}\nComplexity: ${s1Data.complexity}\nDeveloper Experience: ${experience}\nTech Stack: ${technology}\nTarget Deadline: ${adjustedDeadline} days\n\nTEAM MEMBERS FOR DELEGATION:\n${teamText || 'Single Developer'}\n\n⚠️ VALIDATOR FEEDBACK — YOU MUST FIX THESE ISSUES:\n${feedbackText}\n\nPrevious phase plan for reference:\n${JSON.stringify(s2Data.phases)}`,
        temperature: 0.2,
        format: 'json',
        maxTokens: 3000,
        context: 'EXECUTOR_RETRY'
      });
      s2Data = safeParseJSON(s4Response.text, 'Executor Retry Agent');
      const s4Duration = Date.now() - s4Start;

      workflowSteps.push({
        id: 5,
        role: `Executor Agent [${s4Response.provider}]`,
        name: 'Task Correction Pass (Retry)',
        icon: '🔁',
        status: 'completed',
        isRetry: true,
        retryReasons: issueCheck.reasons,
        durationMs: s4Duration,
        summary: `Corrected ${s2Data.phases?.length || 0} phases based on Validator feedback.`,
        details: s2Data
      });

      console.log('Step 5: 🛡️ Validator FINAL audit...');
      const s5Start = Date.now();
      const s5Response = await callLLMWithFallback({
        systemPrompt: VALIDATOR_SYSTEM_PROMPT,
        userPrompt: `Project Overview: ${s1Data.projectOverview}\nPhases & Delegated Tasks: ${JSON.stringify(s2Data.phases)}`,
        temperature: 0.1,
        format: 'json',
        maxTokens: 1500,
        context: 'VALIDATOR_RETRY'
      });
      s3Data = safeParseJSON(s5Response.text, 'Validator Retry Agent');
      const s5Duration = Date.now() - s5Start;

      workflowSteps.push({
        id: 6,
        role: `Validator Agent [${s5Response.provider}]`,
        name: 'Final QA Audit',
        icon: '✅',
        status: 'completed',
        isRetry: true,
        durationMs: s5Duration,
        summary: `Final audit: workload ${s3Data.workloadBalanced !== false ? 'balanced ✅' : 'still unbalanced ⚠️'}, ${s3Data.risks?.length || 0} risks noted.`,
        details: s3Data
      });
    }

    // MERGE ALL STEPS INTO FINAL PLAN OBJECT
    const finalPlan = {
      projectOverview: s1Data.projectOverview,
      complexity: s1Data.complexity,
      estimatedTotalDays: s2Data.estimatedTotalDays || parseInt(deadline, 10) || 30,
      phases: s2Data.phases,
      risks: s3Data.risks,
      testingPlan: s3Data.testingPlan,
    };

    if (!s1Data.deadlineFeasible) {
      finalPlan.userRequestedDeadline = deadline;
      finalPlan.aiSuggestedDeadline = s1Data.suggestedDays;
      finalPlan.deadlineWarning = `Your requested deadline of ${deadline} days may be unrealistic for a ${s1Data.complexity} complexity project. AI suggests ${s1Data.suggestedDays} days.`;
    }

    // Non-blocking content quality check
    const qualityCheck = validateContentQuality(finalPlan, teamMembers);
    if (!qualityCheck.isValid) {
      console.warn('Content quality notice:', qualityCheck.issues);
    }

    const finalResult = {
      plan: finalPlan,
      workflowSteps: workflowSteps
    };

    // 💾 Save result to LRU cache
    setCachedPlan(cacheKey, finalResult);
    console.log('💾 [CACHE] Plan cached for:', projectName);

    return finalResult;

  } catch (error) {
    console.error('❌ AI Pipeline execution error:', error.message);
    throw new Error(`AI Planning Error: ${error.message || 'Service unavailable'}`);
  }
}

const { recordChatMessage, getChatContext } = require('./chatService');

/**
 * AI Assistant Copilot Q&A with Automatic OpenRouter Fallback & MongoDB Long-Term Memory Summary
 */
async function askAssistantWithLLM({
  question,
  sessionId = 'default-session',
  projectId = null,
  projectContext,
  activePlan,
  conversationHistory
}) {
  // 1. Fetch persistent conversation memory & recent history from MongoDB
  const chatContext = await getChatContext({ sessionId, projectId });
  const memorySummary = chatContext.summary || '';

  // 2. Format recent conversation messages (prefer MongoDB recorded messages or fallback to passed history)
  let historyText = '';
  if (chatContext.recentMessages && chatContext.recentMessages.length > 0) {
    historyText = chatContext.recentMessages
      .map(m => `${m.role === 'user' ? 'User' : 'Assistant'}: ${m.text}`)
      .join('\n');
  } else if (Array.isArray(conversationHistory) && conversationHistory.length > 0) {
    historyText = conversationHistory
      .slice(-6)
      .map(msg => `${msg.role === 'user' ? 'User' : 'Assistant'}: ${msg.text}`)
      .join('\n');
  }

  // 3. Construct Context with Rolling Memory Summary
  const assistantPrompt = `PROJECT CONTEXT:
Project Name: ${projectContext?.projectName || 'Project'}
Technology: ${projectContext?.technology || 'N/A'}
Experience Level: ${projectContext?.experience || 'Intermediate'}
Deadline: ${projectContext?.deadline || 'N/A'} days

CURRENT PROJECT PLAN:
${JSON.stringify(activePlan || {}, null, 2)}
${memorySummary ? `\nPREVIOUS CONVERSATION SUMMARY (LONG-TERM MEMORY):\n${memorySummary}\n` : ''}
RECENT DIALOGUE:
${historyText || 'No previous conversation in this session.'}

USER QUESTION:
${question}`;

  const assistantSystemPrompt = `You are a helpful AI project planning assistant. 
Use the project context, current plan, rolling conversation memory, and recent dialogue to give concise, practical answers.`;

  // 4. Generate response via Ollama (or OpenRouter fallback)
  const response = await callLLMWithFallback({
    systemPrompt: assistantSystemPrompt,
    userPrompt: assistantPrompt,
    temperature: 0.5,
    format: null,
    maxTokens: 1500,
    context: 'ASSISTANT_COPILOT'
  });

  const answer = response.text;

  // 5. Persist User question and Assistant response into MongoDB with auto-summarization
  await recordChatMessage({
    sessionId,
    projectId,
    role: 'user',
    content: question
  });

  const chatRecordResult = await recordChatMessage({
    sessionId,
    projectId,
    role: 'assistant',
    content: answer,
    callLLM: callLLMWithFallback
  });

  return {
    answer,
    summary: chatRecordResult.summary || memorySummary,
    provider: response.provider
  };
}

module.exports = {
  validateProjectPlan,
  generateMultiStepPlan,
  askAssistantWithLLM,
  callLLMWithFallback,
  OLLAMA_BASE_URL,
  OLLAMA_MODEL,
  OPENROUTER_MODEL
};